# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

target 'onblast' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!
  pod 'Folly', :podspec => '../node_modules/react-native/third-party-podspecs/Folly.podspec'
  pod 'yoga', :path => '../node_modules/react-native/ReactCommon/yoga/yoga.podspec'
  pod 'React', :path => '../node_modules/react-native', :subspecs => [
    'CxxBridge', # Required For React Native 0.45.0+
    'Core',
    'DevSupport'
    # Add any other subspecs you want to use in your project
  ]

  # Pods for onblast
  pod 'Firebase/Core', '4.13.0'
  pod 'Firebase/Auth'
  pod 'Firebase/Database'
  pod 'Firebase/Storage'

  pod 'RNVectorIcons', :path => '../node_modules/react-native-vector-icons'
  pod 'react-native-camera', path: '../node_modules/react-native-camera'
  pod 'Bolts'
  pod 'FBSDKCoreKit'
  pod 'FBSDKLoginKit'
  pod 'FBSDKShareKit'
#  pod 'GoogleSignIn'

  # pod 'react-native-video', :path => '../node_modules/react-native-video'

  # pod 'BVLinearGradient', :path => '../node_modules/react-native-linear-gradient'

  target 'onblastTests' do
    inherit! :search_paths
    # Pods for testing
  end

end

target 'onblast-tvOS' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for onblast-tvOS

  target 'onblast-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    if target.name == "React"
      target.remove_from_project
    end
  end
end
